name: Orange BDD Framework CI/CD Pipeline

# Trigger pipeline on push to master branch and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

# Environment variables
env:
  MAVEN_OPTS: -Dfile.encoding=UTF-8
  JAVA_OPTS: -Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1

# Jobs configuration
jobs:
  # API Tests Job
  api-tests:
    name: 🔌 API Tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      # Setup Java 19
      - name: ☕ Setup Java 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          
      # Cache Maven dependencies
      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # Display versions
      - name: ℹ️ Display versions
        run: |
          echo "🔍 Environment Information:"
          echo "=========================="
          echo "Java version:"
          java -version
          echo ""
          echo "Maven version:"
          mvn -version
          echo ""
          echo "Current directory:"
          pwd
          
      # Compile project
      - name: 🔨 Compile project
        run: mvn clean compile test-compile -q
        
      # Run API tests
      - name: 🧪 Run API tests
        run: mvn clean test -Dtest=APICucumberRunner -q
        
      # Upload API test results
      - name: 📤 Upload API test results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            target/cucumber-reports/
            target/surefire-reports/
          retention-days: 30
          
      # Upload API HTML report
      - name: 📊 Upload API HTML report
        uses: actions/upload-artifact@v4
        with:
          name: api-html-report
          path: target/cucumber-reports/api-cucumber.html
          retention-days: 30

  # UI Tests Job
  ui-tests:
    name: 🖥️ UI Tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      # Setup Java 19
      - name: ☕ Setup Java 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          
      # Cache Maven dependencies
      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # Display versions
      - name: ℹ️ Display versions
        run: |
          echo "🔍 Environment Information:"
          echo "=========================="
          echo "Java version:"
          java -version
          echo ""
          echo "Maven version:"
          mvn -version
          echo ""
          echo "Current directory:"
          pwd
          
      # Compile project
      - name: 🔨 Compile project
        run: mvn clean compile test-compile -q
        
      # Run UI tests
      - name: 🧪 Run UI tests
        run: mvn clean test -Dtest=UICucumberRunner -q
        
      # Upload UI test results
      - name: 📤 Upload UI test results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            target/cucumber-reports/
            target/surefire-reports/
          retention-days: 30
          
      # Upload UI HTML report
      - name: 📊 Upload UI HTML report
        uses: actions/upload-artifact@v4
        with:
          name: ui-html-report
          path: target/cucumber-reports/ui-cucumber.html
          retention-days: 30

  # Summary Job
  summary:
    name: 📋 Test Summary
    runs-on: ubuntu-latest
    needs: [api-tests, ui-tests]
    if: always()
    
    steps:
      # Checkout code
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      # Download all test artifacts
      - name: 📥 Download test artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-artifacts
          
      # Create summary report
      - name: 📋 Create summary report
        run: |
          cat << EOF > test-summary.md
          # 🚀 Orange BDD Framework Test Summary
          
          ## 🎯 Pipeline Status
          - **API Tests**: ${{ needs.api-tests.result }}
          - **UI Tests**: ${{ needs.ui-tests.result }}
          - **Overall**: ${{ (needs.api-tests.result == 'success' && needs.ui-tests.result == 'success') && '✅ PASSED' || '❌ FAILED' }}
          
          ## 📊 Test Results
          - **API Tests**: Available in \`api-test-results\` artifact
          - **UI Tests**: Available in \`ui-test-results\` artifact
          
          ## 📄 HTML Reports
          - **API Report**: \`api-html-report\` artifact
          - **UI Report**: \`ui-html-report\` artifact
          
          ## 🔗 Artifacts
          All test results and reports are available for download in the workflow artifacts.
          
          **Commit**: ${{ github.sha }}
          **Branch**: ${{ github.ref_name }}
          **Triggered by**: ${{ github.actor }}
          **Execution Time**: $(date)
          EOF
          
      # Upload summary
      - name: 📤 Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md
          retention-days: 90 