name: BDD UI-API Framework CI/CD Pipeline

# Permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one Pages deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

# Trigger pipeline on push to master branch and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

# Environment variables
env:
  MAVEN_OPTS: -Dfile.encoding=UTF-8
  JAVA_OPTS: -Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1

# Jobs configuration
jobs:
  # API Tests Job
  api-tests:
    name: 🔌 API Tests
    runs-on: ubuntu-latest
    env:
      API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
    
    steps:
      # Checkout code
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      # Setup Java 19
      - name: ☕ Setup Java 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          
      # Cache Maven dependencies
      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # Display versions
      - name: ℹ️ Display versions
        run: |
          echo "🔍 Environment Information:"
          echo "=========================="
          echo "Java version:"
          java -version
          echo ""
          echo "Maven version:"
          mvn -version
          echo ""
          echo "Current directory:"
          pwd
          
      # Compile project
      - name: 🔨 Compile project
        run: mvn clean compile test-compile -q
        
      # Run API tests
      - name: 🧪 Run API tests
        run: mvn clean test -Dtest=APICucumberRunner -Dapi.auth.token=${API_AUTH_TOKEN} -q

  # UI Tests Job
  ui-tests:
    name: 🖥️ UI Tests
    runs-on: ubuntu-latest
    env:
      API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
    
    steps:
      # Checkout code
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      # Setup Java 19
      - name: ☕ Setup Java 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          
      # Cache Maven dependencies
      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # Display versions
      - name: ℹ️ Display versions
        run: |
          echo "🔍 Environment Information:"
          echo "=========================="
          echo "Java version:"
          java -version
          echo ""
          echo "Maven version:"
          mvn -version
          echo ""
          echo "Current directory:"
          pwd
          
      # Compile project
      - name: 🔨 Compile project
        run: mvn clean compile test-compile -q
        
      # Run UI tests
      - name: 🧪 Run UI tests
        run: mvn clean test -Dtest=UICucumberRunner -q

      # Upload Cucumber HTML (UI)
        
      # Upload UI test results
      - name: 📤 Upload UI test results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            target/cucumber-reports/
            target/surefire-reports/
          retention-days: 30
          
      # Upload UI HTML report
      - name: 📊 Upload UI HTML report
        uses: actions/upload-artifact@v4
        with:
          name: ui-html-report
          path: target/cucumber-reports/ui-cucumber.html
          retention-days: 30

  

  # Deploy combined Masterthought report to GitHub Pages
  deploy-pages:
    name: 🚀 Deploy Reports to GitHub Pages
    runs-on: ubuntu-latest
    needs: [api-tests, ui-tests]
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Setup Java 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🔨 Build and generate combined report (UI + API)
        run: mvn -P dev -Dmaven.test.failure.ignore=true -q clean test verify

      - name: 🪄 Prepare Pages structure (root index + per-report index)
        run: |
          ROOT_DIR=target/reports
          UI_DIR=$ROOT_DIR/ui/cucumber-html-reports
          API_DIR=$ROOT_DIR/api/cucumber-html-reports
          mkdir -p "$ROOT_DIR"
          # Per-report index pages
          if [ -f "$UI_DIR/overview-features.html" ]; then
            cp "$UI_DIR/overview-features.html" "$UI_DIR/index.html"
          fi
          if [ -f "$API_DIR/overview-features.html" ]; then
            cp "$API_DIR/overview-features.html" "$API_DIR/index.html"
          fi
          # Root index with links to both reports
          cat > "$ROOT_DIR/index.html" << 'EOF'
          <!doctype html>
          <html><head><meta charset="utf-8"><title>Pulsar Reports</title>
          <style>body{font-family:Arial,Helvetica,sans-serif;margin:24px} a{display:block;margin:8px 0;font-size:18px}</style>
          </head><body>
            <h1>Pulsar Test Reports</h1>
            <a href="ui/cucumber-html-reports/index.html">UI Report</a>
            <a href="api/cucumber-html-reports/index.html">API Report</a>
          </body></html>
          EOF

      - name: ⚙️ Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: 📦 Upload Pages artifact (Masterthought reports)
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/reports

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4